/******************************************************************************/
/***          Generated by IBExpert 2009.08.28 12.10.2009 18:25:55          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE 'C:\devel\OptionTrader\ADOption\db\AD.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_AD_LOG_QUOTE_ID;
SET GENERATOR GEN_AD_LOG_QUOTE_ID TO 0;



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

SET TERM ^ ;


CREATE PROCEDURE GET_LOG_QUOTES (
    SECS INTEGER)
RETURNS (
    QUOTE_UPDATE_TYPE VARCHAR(10),
    FUT_LAST_PRICE FLOAT,
    FUT_BEST_SELL_PRICE FLOAT,
    FUT_BEST_BUY_PRICE FLOAT,
    OPT_CODE VARCHAR(256),
    OPT_TYPE VARCHAR(10),
    OPT_STRIKE FLOAT,
    LOG_DT TIMESTAMP,
    OPT_MAT_DT TIMESTAMP,
    OPT_LAST_PRICE FLOAT,
    OPT_IMPL_VOL FLOAT,
    OPT_BEST_SELL_PRICE FLOAT,
    OPT_SELL_IMPL_VOL FLOAT,
    OPT_BEST_BUY_PRICE FLOAT,
    OPT_BUY_IMPL_VOL FLOAT)
AS
BEGIN
  SUSPEND;
END^


SET TERM ; ^


/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE AD_ABNORMAL_DATES (
    "ab_date"        TIMESTAMP NOT NULL,
    "i_last_update"  INTEGER
);

CREATE TABLE AD_ACCOUNTS (
    "treaty"         INTEGER NOT NULL,
    "full_name"      VARCHAR(255),
    "i_last_update"  INTEGER,
    "start_margin"   FLOAT,
    "msg_margin"     FLOAT,
    "min_margin"     FLOAT,
    "unknown_field"  VARCHAR(255)
);

CREATE TABLE AD_ACTIVES (
    "p_code"         VARCHAR(255) NOT NULL,
    "p_name"         VARCHAR(255),
    "ANSI_name"      VARCHAR(255),
    "expared"        VARCHAR(255),
    "serial_group"   VARCHAR(255),
    "i_last_update"  INTEGER,
    "em_code"        VARCHAR(255),
    "at_code"        VARCHAR(255),
    "emission_no"    INTEGER,
    "transh_no"      INTEGER,
    "at_name"        VARCHAR(255),
    "reg_code"       VARCHAR(255),
    "buyback_price"  FLOAT,
    "buyback_date"   TIMESTAMP,
    "nominal_curr"   VARCHAR(255),
    "mult"           INTEGER,
    "divid"          INTEGER,
    "strike"         FLOAT,
    "contr_descr"    VARCHAR(255),
    "unknown_field"  VARCHAR(255)
);

CREATE TABLE AD_BALANCE (
    "acc_code"                   VARCHAR(255) NOT NULL,
    "p_code"                     VARCHAR(255) NOT NULL,
    "place_code"                 VARCHAR(255) NOT NULL,
    "income_rest"                FLOAT,
    "real_rest"                  FLOAT,
    "plan_rest"                  FLOAT,
    "brutto_rest"                FLOAT,
    "turnover"                   FLOAT,
    "balance_price"              FLOAT,
    "paper_no"                   INTEGER,
    "i_last_update"              INTEGER,
    "forword_rest"               FLOAT,
    "assessed_price"             FLOAT,
    "real_vol"                   FLOAT,
    "forword_vol"                FLOAT,
    "bal_forword_vol"            FLOAT,
    "profit_vol"                 FLOAT,
    "treaty"                     INTEGER,
    "prev_close"                 FLOAT,
    "in_bids"                    FLOAT,
    "in_offers"                  FLOAT,
    "netto_rest"                 FLOAT,
    "nkd"                        FLOAT,
    "bought"                     FLOAT,
    "sold"                       FLOAT,
    "daily_pl"                   FLOAT,
    "income_pl"                  FLOAT,
    "income_vol"                 FLOAT,
    "price_koef"                 FLOAT,
    "reserved_for_backward_cap"  FLOAT,
    "pl"                         FLOAT,
    "nkd_inc"                    FLOAT,
    "curr_rate"                  FLOAT,
    "price_koef_pl"              FLOAT,
    "var_margin"                 FLOAT,
    "var_margin_pc"              FLOAT,
    "unknown_field"              FLOAT
);

CREATE TABLE AD_BOARDS (
    "board_code"     VARCHAR(255) NOT NULL,
    "place_code"     VARCHAR(255),
    "board_name"     VARCHAR(255),
    "tax"            FLOAT,
    "price_type"     VARCHAR(255),
    "i_last_update"  INTEGER,
    "unknown_field"  VARCHAR(255)
);

CREATE TABLE AD_CHAT_THEMES (
    "theme_code"         VARCHAR(255) NOT NULL,
    "theme_name"         VARCHAR(255),
    "i_last_update"      INTEGER,
    "disable_selection"  VARCHAR(255),
    "unknown_field"      VARCHAR(255)
);

CREATE TABLE AD_CURR (
    "curr_code"      VARCHAR(255) NOT NULL,
    "curr_name"      VARCHAR(255),
    "i_last_update"  INTEGER
);

CREATE TABLE AD_DOC_TEMPLATES (
    "doc_id"         VARCHAR(255) NOT NULL,
    "data"           VARCHAR(4095),
    "i_last_update"  INTEGER
);

CREATE TABLE AD_EMITENTS (
    "em_code"         VARCHAR(255) NOT NULL,
    "short_name"      VARCHAR(255),
    "full_name"       VARCHAR(255),
    "short_name_eng"  VARCHAR(255),
    "ind_code"        VARCHAR(255),
    "www"             VARCHAR(255),
    "country"         VARCHAR(255),
    "i_last_update"   INTEGER
);

CREATE TABLE AD_EXCHANGE_CONTRAGENTS (
    "ex_code"        VARCHAR(255) NOT NULL,
    "firm_code"      VARCHAR(255) NOT NULL,
    "firm_name"      VARCHAR(255),
    "status"         VARCHAR(255),
    "i_last_update"  INTEGER,
    "place_code"     VARCHAR(255)
);

CREATE TABLE AD_EXCHENGES (
    "ex_code"        VARCHAR(255) NOT NULL,
    "ex_name"        VARCHAR(255),
    "i_last_update"  INTEGER,
    "country_code"   VARCHAR(255)
);

CREATE TABLE AD_LOG_QUOTE (
    "pk_log_quote"        INTEGER NOT NULL,
    "quote_update_type"   VARCHAR(10) NOT NULL,
    "log_dt"              TIMESTAMP NOT NULL,
    "fut_no"              INTEGER NOT NULL,
    "fut_code"            VARCHAR(256) NOT NULL,
    "fut_last_price"      FLOAT NOT NULL,
    "fut_best_sell_price" FLOAT NOT NULL,
    "fut_best_buy_price"  FLOAT NOT NULL,
    "fut_sellers"         VARCHAR(256),
    "fut_buyers"          VARCHAR(256),
    "opt_no"              INTEGER NOT NULL,
    "opt_code"            VARCHAR(256) NOT NULL,
    "opt_type"            VARCHAR(10) NOT NULL,
    "opt_strike"          FLOAT NOT NULL,
    "opt_mat_dt"          TIMESTAMP NOT NULL,
    "opt_last_price"      FLOAT NOT NULL,
    "opt_best_sell_price" FLOAT NOT NULL,
    "opt_best_buy_price"  FLOAT NOT NULL,
    "opt_sellers"         VARCHAR(256),
    "opt_buyers"          VARCHAR(256),
    "opt_impl_vol"        FLOAT NOT NULL,
    "opt_sell_impl_vol"   FLOAT NOT NULL,
    "opt_buy_impl_vol"    FLOAT NOT NULL
);

CREATE TABLE AD_MY_CHAT (
    "mes_no"         INTEGER NOT NULL,
    "to_sys_name"    VARCHAR(255),
    "from_sys_name"  VARCHAR(255),
    "subject"        VARCHAR(255),
    "body"           VARCHAR(255),
    "show_window"    VARCHAR(255),
    "color"          INTEGER,
    "type"           VARCHAR(255),
    "end_date"       TIMESTAMP,
    "db_date"        VARCHAR(255),
    "i_last_update"  INTEGER,
    "to_user_id"     INTEGER,
    "from_user_id"   INTEGER
);

CREATE TABLE AD_MY_CURRENT_TRADES (
    "trd_no"         INTEGER NOT NULL,
    "paper_no"       INTEGER,
    "qty"            INTEGER,
    "price"          FLOAT,
    "ts_time"        VARCHAR(255),
    "i_last_update"  INTEGER,
    "change"         INTEGER,
    "type"           INTEGER
);

CREATE TABLE AD_MY_QUOTE_QUEUES (
    "paper_no"       INTEGER NOT NULL,
    "price"          FLOAT,
    "buy_qty"        INTEGER,
    "sell_qty"       INTEGER,
    "i_last_update"  INTEGER,
    "yield"          FLOAT
);

CREATE TABLE AD_MY_QUOTES (
    "paper_no"               INTEGER NOT NULL,
    "open_price"             FLOAT,
    "last_price"             FLOAT,
    "avg_price"              FLOAT,
    "close_price"            FLOAT,
    "change"                 FLOAT,
    "max_deal"               FLOAT,
    "min_deal"               FLOAT,
    "sum_qty"                FLOAT,
    "sum_volume"             FLOAT,
    "last_qty"               INTEGER,
    "no_deal"                INTEGER,
    "sell_qty"               INTEGER,
    "buy_qty"                INTEGER,
    "sell"                   FLOAT,
    "buy"                    FLOAT,
    "reserved_backward_cap"  VARCHAR(255),
    "i_last_update"          INTEGER,
    "high_bid"               FLOAT,
    "low_offer"              FLOAT,
    "prev_price"             FLOAT,
    "yield"                  FLOAT,
    "avg_yield"              FLOAT,
    "close_yield"            FLOAT,
    "price2prev_avg"         FLOAT,
    "buy_sqty"               INTEGER,
    "buy_count"              INTEGER,
    "sell_sqty"              INTEGER,
    "sell_count"             INTEGER,
    "status"                 INTEGER,
    "market_watch"           FLOAT,
    "euro_spread"            FLOAT,
    "open_pos_qty"           INTEGER,
    "volatility"             FLOAT,
    "theor_price"            FLOAT,
    "assessed_price"         FLOAT
);

CREATE TABLE AD_MY_REQUEST_TYPES (
    "ord_type"       VARCHAR(255) NOT NULL,
    "description"    VARCHAR(255),
    "i_last_update"  INTEGER
);

CREATE TABLE AD_NEWS (
    "new_no"         INTEGER NOT NULL,
    "stripe_code"    VARCHAR(255),
    "provider"       VARCHAR(255),
    "db_data"        TIMESTAMP,
    "topic"          VARCHAR(255),
    "subject"        VARCHAR(255),
    "i_last_update"  INTEGER,
    "important"      VARCHAR(255)
);

CREATE TABLE AD_ORDER_STATUSES (
    "ord_status"     VARCHAR(255) NOT NULL,
    "description"    VARCHAR(255),
    "i_last_update"  INTEGER
);

CREATE TABLE AD_ORDERS (
    "ord_no"               INTEGER NOT NULL,
    "acc_code"             VARCHAR(255),
    "type"                 VARCHAR(255),
    "status"               VARCHAR(255),
    "b_s"                  VARCHAR(255),
    "price"                FLOAT,
    "qty"                  INTEGER,
    "nkd"                  FLOAT,
    "rest"                 INTEGER,
    "rest_nkd"             FLOAT,
    "portfolio"            VARCHAR(255),
    "ts_time"              TIMESTAMP,
    "comments"             VARCHAR(255),
    "place_code"           VARCHAR(255),
    "p_code"               VARCHAR(255),
    "i_last_update"        INTEGER,
    "last_date"            TIMESTAMP,
    "stop_price"           FLOAT,
    "price_curr"           VARCHAR(255),
    "non_exch"             VARCHAR(255),
    "blank"                VARCHAR(255),
    "actv_grow_price"      FLOAT,
    "actv_down_price"      FLOAT,
    "actv_time"            TIMESTAMP,
    "actv_kld_order_no"    INTEGER,
    "actv_stld_order_no"   INTEGER,
    "drop_grow_price"      FLOAT,
    "drop_down_price"      FLOAT,
    "drop_time"            TIMESTAMP,
    "drop_kld_order_no"    INTEGER,
    "drop_stld_order_no"   INTEGER,
    "updt_grow_price"      FLOAT,
    "updt_down_price"      FLOAT,
    "updt_time"            TIMESTAMP,
    "updt_kld_order_no"    INTEGER,
    "updt_stld_order_no"   INTEGER,
    "updt_new_price"       FLOAT,
    "fee"                  FLOAT,
    "rest_fee"             FLOAT,
    "volume"               FLOAT,
    "net_value"            FLOAT,
    "firm_code"            VARCHAR(255),
    "cupon_rate"           VARCHAR(255),
    "trailing_level"       FLOAT,
    "trailing_slippage"    FLOAT,
    "instr"                VARCHAR(255),
    "treaty"               INTEGER,
    "sys_name"             VARCHAR(255),
    "limits_check"         VARCHAR(255),
    "init_price"           FLOAT,
    "ord_type"             VARCHAR(255),
    "yield"                FLOAT,
    "repo_days"            INTEGER,
    "repo_ammount"         FLOAT,
    "repo_discount"        FLOAT,
    "repo_ts_no"           VARCHAR(255),
    "repo_low_discount"    FLOAT,
    "repo_high_discount"   FLOAT,
    "contragent_acc_code"  VARCHAR(255),
    "unknown_field_1"      FLOAT,
    "unknown_field_2"      INTEGER
);

CREATE TABLE AD_PAPER_STATUSES (
    "status"         VARCHAR(255) NOT NULL,
    "description"    VARCHAR(255),
    "i_last_update"  INTEGER,
    "num_status"     INTEGER,
    "unknown_field"  VARCHAR(255)
);

CREATE TABLE AD_PAPERS (
    "paper_no"         INTEGER NOT NULL,
    "p_code"           VARCHAR(255),
    "place_code"       VARCHAR(255),
    "ts_p_code"        VARCHAR(255),
    "board_code"       VARCHAR(255),
    "lot_size"         INTEGER,
    "decimals"         INTEGER,
    "nkd"              FLOAT,
    "cup_size"         FLOAT,
    "cup_date"         TIMESTAMP,
    "cup_period"       INTEGER,
    "nominal"          FLOAT,
    "mat_date"         TIMESTAMP,
    "allow_pawn"       VARCHAR(255),
    "sum_limit"        FLOAT,
    "i_last_update"    INTEGER,
    "expired"          VARCHAR(255),
    "allow_short"      VARCHAR(255),
    "firm_code"        VARCHAR(255),
    "mk_short"         FLOAT,
    "mk_long"          FLOAT,
    "mk_short_min"     FLOAT,
    "mk_long_min"      FLOAT,
    "mk_short_repo"    FLOAT,
    "mk_long_repo"     FLOAT,
    "price_step"       FLOAT,
    "create_date"      INTEGER,
    "base_paper_no"    INTEGER,
    "just_inserted"    INTEGER,
    "go_buy"           FLOAT,
    "go_sell"          FLOAT,
    "go_covered"       FLOAT,
    "go_uncovered"     FLOAT,
    "price_step_cost"  FLOAT
);

CREATE TABLE AD_POSITIONS (
    "acc_code"       VARCHAR(255) NOT NULL,
    "place_code"     VARCHAR(255) NOT NULL,
    "depo_acc"       VARCHAR(255),
    "i_last_update"  INTEGER
);

CREATE TABLE AD_SUB_ACCOUNTS (
    "acc_code"         VARCHAR(255) NOT NULL,
    "nick_name"        VARCHAR(255),
    "treaty"           INTEGER,
    "toy"              VARCHAR(255),
    "allow_debet"      VARCHAR(255),
    "i_last_update"    INTEGER,
    "unsecured_limit"  FLOAT,
    "start_margin"     FLOAT,
    "msg_margin"       FLOAT,
    "min_margin"       FLOAT,
    "unknown_field"    FLOAT
);

CREATE TABLE AD_TRADE_PLACES (
    "place_code"             VARCHAR(255) NOT NULL,
    "curr_code"              VARCHAR(255),
    "place_name"             VARCHAR(255),
    "info_price"             FLOAT,
    "status"                 VARCHAR(255),
    "last_session_date"      TIMESTAMP,
    "t_acc_prefix"           VARCHAR(255),
    "prev_session_date"      TIMESTAMP,
    "ex_code"                VARCHAR(255),
    "depo_code"              VARCHAR(255),
    "i_last_update"          INTEGER,
    "allow_trade"            VARCHAR(255),
    "vendor_code"            VARCHAR(255),
    "dp_name"                VARCHAR(255),
    "allow_market_orders"    VARCHAR(255),
    "allow_nomarket_orders"  VARCHAR(255),
    "balance_place_code"     VARCHAR(255),
    "balance_place_name"     VARCHAR(255),
    "market_name"            VARCHAR(255),
    "allow_rpc"              VARCHAR(255),
    "allow_rpc_auction"      VARCHAR(255),
    "allow_auction"          VARCHAR(255),
    "quote_place_code"       VARCHAR(255),
    "allow_all_trades"       VARCHAR(255)
);

CREATE TABLE AD_TRADE_TYPES (
    "trd_type_code"         VARCHAR(255) NOT NULL,
    "trd_type_describtion"  VARCHAR(255),
    "i_last_update"         INTEGER,
    "trd_type_num_code"     INTEGER
);

CREATE TABLE AD_TRADES (
    "trd_no"           INTEGER NOT NULL,
    "ord_no"           INTEGER,
    "acc_code"         VARCHAR(255),
    "ts_no"            VARCHAR(255),
    "trd_type_code"    VARCHAR(255),
    "b_s"              VARCHAR(255),
    "qty"              INTEGER,
    "price"            FLOAT,
    "ts_tax"           FLOAT,
    "nkd"              FLOAT,
    "ts_time"          TIMESTAMP,
    "comments"         VARCHAR(255),
    "portfolio"        VARCHAR(255),
    "p_code"           VARCHAR(255),
    "place_code"       VARCHAR(255),
    "settlement_date"  TIMESTAMP,
    "settlemented"     VARCHAR(255),
    "bank_tax"         FLOAT,
    "depo_tax"         FLOAT,
    "i_last_update"    INTEGER,
    "price_curr"       VARCHAR(255),
    "non_exch"         VARCHAR(255),
    "comiss"           FLOAT,
    "fee"              FLOAT,
    "net_value"        FLOAT,
    "volume"           FLOAT,
    "pl"               FLOAT,
    "treaty"           INTEGER,
    "paper_no"         INTEGER,
    "firm_code"        VARCHAR(255),
    "money_rest"       FLOAT,
    "paper_rest"       INTEGER,
    "unknown_field"    INTEGER
);


/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE GET_LOG_QUOTES (
    SECS INTEGER)
RETURNS (
    QUOTE_UPDATE_TYPE VARCHAR(10),
    FUT_LAST_PRICE FLOAT,
    FUT_BEST_SELL_PRICE FLOAT,
    FUT_BEST_BUY_PRICE FLOAT,
    OPT_CODE VARCHAR(256),
    OPT_TYPE VARCHAR(10),
    OPT_STRIKE FLOAT,
    LOG_DT TIMESTAMP,
    OPT_MAT_DT TIMESTAMP,
    OPT_LAST_PRICE FLOAT,
    OPT_IMPL_VOL FLOAT,
    OPT_BEST_SELL_PRICE FLOAT,
    OPT_SELL_IMPL_VOL FLOAT,
    OPT_BEST_BUY_PRICE FLOAT,
    OPT_BUY_IMPL_VOL FLOAT)
AS
declare variable TIME_FRAME integer;
declare variable OLD_TIME_FRAME integer;
declare variable OLD_OPT_CODE varchar(256);
begin
    IF (:secs = 0 OR :secs IS NULL) THEN
        secs = 1;
    old_time_frame = 0;
    FOR SELECT
           DATEDIFF(SECOND, TIMESTAMP '01.01.2000 00:00:00', l."log_dt")/:secs,
           l."quote_update_type", l."fut_last_price", l."fut_best_sell_price",
           l."fut_best_buy_price", l."opt_code", l."opt_type", l."opt_strike", l."log_dt",
           l."opt_mat_dt", l."opt_last_price", l."opt_impl_vol", l."opt_best_sell_price",
           l."opt_sell_impl_vol", l."opt_best_buy_price", l."opt_buy_impl_vol"
      FROM ad_log_quote AS l
    ORDER BY l."opt_code", l."log_dt"
    INTO :time_frame, :quote_update_type, :fut_last_price, :fut_best_sell_price,
         :fut_best_buy_price, :opt_code, :opt_type, :opt_strike, :log_dt,
         :opt_mat_dt, :opt_last_price, :opt_impl_vol, :opt_best_sell_price,
         :opt_sell_impl_vol, :opt_best_buy_price, :opt_buy_impl_vol
    DO
    BEGIN
        if (old_opt_code <> opt_code) then
            old_time_frame = 0;
        if (old_time_frame = 0 or old_time_frame <> time_frame) then
        begin
            old_time_frame = time_frame;
            suspend;
        end
    END
end^

SET TERM ; ^


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE AD_ABNORMAL_DATES ADD CONSTRAINT AD_ABNORMAL_DATES_PK PRIMARY KEY ("ab_date");
ALTER TABLE AD_ACCOUNTS ADD CONSTRAINT AD_ACCOUNTS_PK PRIMARY KEY ("treaty");
ALTER TABLE AD_ACTIVES ADD CONSTRAINT AD_ACTIVES_PK PRIMARY KEY ("p_code");
ALTER TABLE AD_BALANCE ADD CONSTRAINT AD_BALANCE_PK PRIMARY KEY ("acc_code", "p_code", "place_code");
ALTER TABLE AD_BOARDS ADD CONSTRAINT AD_BOARDS_PK PRIMARY KEY ("board_code");
ALTER TABLE AD_CHAT_THEMES ADD CONSTRAINT AD_CHAT_THEMES_PK PRIMARY KEY ("theme_code");
ALTER TABLE AD_CURR ADD CONSTRAINT AD_CURR_PK PRIMARY KEY ("curr_code");
ALTER TABLE AD_DOC_TEMPLATES ADD CONSTRAINT AD_DOC_TEMPLATES_PK PRIMARY KEY ("doc_id");
ALTER TABLE AD_EMITENTS ADD CONSTRAINT AD_EMITENTS_PK PRIMARY KEY ("em_code");
ALTER TABLE AD_EXCHANGE_CONTRAGENTS ADD CONSTRAINT AD_EXCHANGE_CONTRAGENTS_PK PRIMARY KEY ("ex_code", "firm_code");
ALTER TABLE AD_EXCHENGES ADD CONSTRAINT AD_EXCHENGES_PK PRIMARY KEY ("ex_code");
ALTER TABLE AD_LOG_QUOTE ADD CONSTRAINT PK_AD_LOG_QUOTE PRIMARY KEY ("pk_log_quote");
ALTER TABLE AD_MY_CHAT ADD CONSTRAINT AD_CHAT_PK PRIMARY KEY ("mes_no");
ALTER TABLE AD_MY_CURRENT_TRADES ADD CONSTRAINT AD_CURRENT_TRADES_PK PRIMARY KEY ("trd_no");
ALTER TABLE AD_MY_QUOTES ADD CONSTRAINT AD_QUOTES_PK PRIMARY KEY ("paper_no");
ALTER TABLE AD_MY_QUOTE_QUEUES ADD CONSTRAINT AD_QUOTE_QUEUES_PK PRIMARY KEY ("paper_no");
ALTER TABLE AD_MY_REQUEST_TYPES ADD CONSTRAINT AD_REQUEST_TYPES_PK PRIMARY KEY ("ord_type");
ALTER TABLE AD_NEWS ADD CONSTRAINT AD_NEWS_PK PRIMARY KEY ("new_no");
ALTER TABLE AD_ORDERS ADD CONSTRAINT AD_ORDERS_PK PRIMARY KEY ("ord_no");
ALTER TABLE AD_ORDER_STATUSES ADD CONSTRAINT AD_ORDER_STATUSES_PK PRIMARY KEY ("ord_status");
ALTER TABLE AD_PAPERS ADD CONSTRAINT AD_PAPERS_PK PRIMARY KEY ("paper_no");
ALTER TABLE AD_PAPER_STATUSES ADD CONSTRAINT AD_PAPER_STATUSES_PK PRIMARY KEY ("status");
ALTER TABLE AD_POSITIONS ADD CONSTRAINT AD_POSITIONS_PK PRIMARY KEY ("acc_code", "place_code");
ALTER TABLE AD_SUB_ACCOUNTS ADD CONSTRAINT AD_SUB_ACCOUNTS_PK PRIMARY KEY ("acc_code");
ALTER TABLE AD_TRADES ADD CONSTRAINT AD_TRADES_PK PRIMARY KEY ("trd_no");
ALTER TABLE AD_TRADE_PLACES ADD CONSTRAINT AD_TRADE_PLACES_PK PRIMARY KEY ("place_code");
ALTER TABLE AD_TRADE_TYPES ADD CONSTRAINT AD_TRADE_TYPES_PK PRIMARY KEY ("trd_type_code");
